#!/usr/bin/bash
#
# Get current path, which is presumably where this script being invoked from.
# Define location of this (extended) workspace for the additional packages.
# Adjust NOETICPATH if it is elsewhere.  
#
# Define group of the user.  Currently using Debian/linux default for user.
#
export OWD=`pwd`
export IVAPATH=/opt/ros1/ivalab
export NOETICPATH=/opt/ros/noetic

export MYGROUP=$USER

source $NOETICPATH/setup.bash

# First get and install the Sophus library.  We are putting it into a local source
# directory called `lsrc` and then installing it to /usr/local/ as the sensible option.
#
#sudo apt-get install -y ccache libmetis-dev
#mkdir -p lsrc
#cd lsrc
#git clone https://github.com/strasdat/Sophus
#cd Sophus
#export SOPHUSPATH=`pwd`
#./scripts/install_ubuntu_deps_incl_ceres.sh
#cd $SOPHUSPATH
#mkdir -p build
# cd build
# cmake ../
# make 
# sudo make install
#
# REQUIRES NEWER VERSION OF CMAKE THAN Ubuntu 22.04 PROVIDES.  GOING WITH APT PACKAGE
# FROM NOETIC/FOCAL APT DATABASE.
# IF YOU REALLY WANT TO COMPILE FROM SOURCE, THEN ADJUST FIRST LINE OF CMakeLists.txt
# TO BE 3.22 AND NOT 3.24.  IT APPEARS TO WORK JUST FINE.
# THE ABOVE LINES OF CODE TAKE A WHILE.
#
# Getting sophus from packages seems to work fine.  Using below.

sudo apt-get install -y ros-noetic-sophus

# Makes an extended workspace under assumption that base workspace is in NOETICPATH.
# The extended workspace goes in IVAPATH

sudo mkdir -p $IVAPATH && sudo chown -R $USER:$MYGROUP $IVAPATH
cd $IVAPATH
catkin init
catkin config --mkdirs --extend $NOETICPATH --cmake-args -DCMAKE_BUILD_TYPE="Release" \
		-DCMAKE_CXX_FLAGS_RELEASE="-O2 -g" -DCMAKE_C_FLAGS_RELEASE="-O2 -g"


wstool init src
wstool merge -t src https://raw.githubusercontent.com/ivaROS/noetic_turtlebot/main/noetic-additional.rosinstall 
wstool merge -t src https://raw.githubusercontent.com/ivaROS/noetic_turtlebot/main/turtlebot.rosinstall 
wstool update -t src -j20

# The patches below adjust the CMakeLists.txt file to have the default build as Fortress.
# For some funny reason the Fortress CMAKE definitions are missing, and the default build
# is some super old version of Gazebo (v4 Ignition maybe).  That causes all sorts of
# problems.  The quick/nasty fix was to just override the default to be Igntion Fortress.
#
patch src/ros_gz/ros_ign_gazebo/CMakeLists.txt < $OWD/patches/ros_ign_gazebo.patch
patch src/ros_gz/ros_ign_bridge/CMakeLists.txt < $OWD/patches/ros_ign_bridge.patch
patch src/ros_gz/ros_ign_image/CMakeLists.txt < $OWD/patches/ros_ign_image.patch

rm -Rf src/kobuki_ros/kobuki_desktop/kobuki_gazebo*
# Have not yet fixed Gazebo specifications to work with modern version.  Deleting until fixed.

rosdep update
rosdep install --from-paths src --ignore-src -y -r

# Correct some of the source file contents to prevent compile failures.
#
patch src/ecl_core/ecl_eigen/CMakeLists.txt < $OWD/patches/ecl_eigen.patch

export HPATH="$IVAPATH/src/gazebo-ignition-ros/semantic_segmentation_husky/sdf"
export NEWHUSKY="$HPATH/husky.sdf"
sed -i "s|husky\.sdf|$NEWHUSKY|g" $HPATH/world.sdf
cp $OWD/patches/husky_teleop.py $HPATH/../scripts/

# Build the workspace!!!
catkin build
